Search.appendIndex(
    [
                {
            "fqsen": "\\API\\API",
            "name": "API",
            "summary": "Class\u0020API",
            "url": "classes/API-API.html"
        },                {
            "fqsen": "\\API\\API\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "API\u0020constructor.",
            "url": "classes/API-API.html#method___construct"
        },                {
            "fqsen": "\\API\\API\u003A\u003A\u0024endpoint",
            "name": "endpoint",
            "summary": "",
            "url": "classes/API-API.html#property_endpoint"
        },                {
            "fqsen": "\\API\\API\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/API-API.html#property_request"
        },                {
            "fqsen": "\\API\\API\u003A\u003A\u0024body",
            "name": "body",
            "summary": "",
            "url": "classes/API-API.html#property_body"
        },                {
            "fqsen": "\\API\\API\u003A\u003A\u0024params",
            "name": "params",
            "summary": "",
            "url": "classes/API-API.html#property_params"
        },                {
            "fqsen": "\\API\\API\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/API-API.html#method_execute"
        },                {
            "fqsen": "\\API\\API\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/API-API.html#property_db"
        },                {
            "fqsen": "\\API\\API\u003A\u003A\u0024requesterID",
            "name": "requesterID",
            "summary": "",
            "url": "classes/API-API.html#property_requesterID"
        },                {
            "fqsen": "\\API\\API\u003A\u003A\u0024manager",
            "name": "manager",
            "summary": "",
            "url": "classes/API-API.html#property_manager"
        },                {
            "fqsen": "\\Auth",
            "name": "Auth",
            "summary": "",
            "url": "classes/Auth.html"
        },                {
            "fqsen": "\\Auth\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Auth\u0020constructor.",
            "url": "classes/Auth.html#method___construct"
        },                {
            "fqsen": "\\Auth\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "",
            "url": "classes/Auth.html#method_check"
        },                {
            "fqsen": "\\Auth\u003A\u003Asignout\u0028\u0029",
            "name": "signout",
            "summary": "",
            "url": "classes/Auth.html#method_signout"
        },                {
            "fqsen": "\\Auth\u003A\u003AsetAuthSession\u0028\u0029",
            "name": "setAuthSession",
            "summary": "",
            "url": "classes/Auth.html#method_setAuthSession"
        },                {
            "fqsen": "\\Auth\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Auth.html#method_create"
        },                {
            "fqsen": "\\Auth\u003A\u003Asignin\u0028\u0029",
            "name": "signin",
            "summary": "",
            "url": "classes/Auth.html#method_signin"
        },                {
            "fqsen": "\\Auth\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Auth.html#property_db"
        },                {
            "fqsen": "\\Auth\u003A\u003A\u0024hash",
            "name": "hash",
            "summary": "",
            "url": "classes/Auth.html#property_hash"
        },                {
            "fqsen": "\\Auth\u003A\u003A\u0024session",
            "name": "session",
            "summary": "",
            "url": "classes/Auth.html#property_session"
        },                {
            "fqsen": "\\Database",
            "name": "Database",
            "summary": "",
            "url": "classes/Database.html"
        },                {
            "fqsen": "\\Database\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Database\u0020constructor.",
            "url": "classes/Database.html#method___construct"
        },                {
            "fqsen": "\\Database\u003A\u003Aquery\u0028\u0029",
            "name": "query",
            "summary": "",
            "url": "classes/Database.html#method_query"
        },                {
            "fqsen": "\\Database\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/Database.html#property_table"
        },                {
            "fqsen": "\\Database\u003A\u003A\u0024row",
            "name": "row",
            "summary": "",
            "url": "classes/Database.html#property_row"
        },                {
            "fqsen": "\\Database\u003A\u003A\u0024selection",
            "name": "selection",
            "summary": "",
            "url": "classes/Database.html#property_selection"
        },                {
            "fqsen": "\\Database\u003A\u003ArandomTuple\u0028\u0029",
            "name": "randomTuple",
            "summary": "",
            "url": "classes/Database.html#method_randomTuple"
        },                {
            "fqsen": "\\Database\u003A\u003Ainsert\u0028\u0029",
            "name": "insert",
            "summary": "function\u0020to\u0020insert\u0020data\u0020in\u0020table.\u0020function\u0020must\u0020be\u0020called\u0020like\u0020so\u003A",
            "url": "classes/Database.html#method_insert"
        },                {
            "fqsen": "\\Database\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "function\u0020to\u0020update\u0020data\u0020in\u0020table.\u0020function\u0020must\u0020be\u0020called\u0020with\u0020update\u002Dvalues,\u0020and\u0020where\u002Darrays.",
            "url": "classes/Database.html#method_update"
        },                {
            "fqsen": "\\Database\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/Database.html#method_delete"
        },                {
            "fqsen": "\\Database\u003A\u003A\u0024innerJoin",
            "name": "innerJoin",
            "summary": "",
            "url": "classes/Database.html#property_innerJoin"
        },                {
            "fqsen": "\\Database\u003A\u003Awhere\u0028\u0029",
            "name": "where",
            "summary": "Usage\u003A\u0020\u0024db\u002D\u003Etable\u0028\u0027employees\u0027\u0029\u002D\u003Ewhere\u0028\u005B\u0022EmployeeID\u0022,\u0022\u003E\u0022,0\u005D,\u005B\u0022FirstName\u0022,\u0022\u003D\u0022,\u0022Rita\u0022\u005D\u0029\u002D\u003Eget\u0028\u0029\u003B\nUse\u0020for\u0020SELECT\u0020data\u0020from\u0020database\u0020in\u0020combination\u0020met\u0020\u002D\u003Eget\u0028\u0029\u0020of\u0020\u002D\u003Efirst\u0028\u0029\u003B",
            "url": "classes/Database.html#method_where"
        },                {
            "fqsen": "\\Database\u003A\u003Aincrement\u0028\u0029",
            "name": "increment",
            "summary": "",
            "url": "classes/Database.html#method_increment"
        },                {
            "fqsen": "\\Database\u003A\u003A\u0024distinct",
            "name": "distinct",
            "summary": "",
            "url": "classes/Database.html#property_distinct"
        },                {
            "fqsen": "\\Database\u003A\u003A\u0024group",
            "name": "group",
            "summary": "",
            "url": "classes/Database.html#property_group"
        },                {
            "fqsen": "\\Database\u003A\u003A\u0024order",
            "name": "order",
            "summary": "",
            "url": "classes/Database.html#property_order"
        },                {
            "fqsen": "\\Database\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Database.html#method_count"
        },                {
            "fqsen": "\\Database\u003A\u003Aexists\u0028\u0029",
            "name": "exists",
            "summary": "usage\u0020\u002D\u003Eexists\u0028\u005B\u0027Fieldname\u0027\u003D\u003E\u0024value\u005D\u0029",
            "url": "classes/Database.html#method_exists"
        },                {
            "fqsen": "\\Database\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Database.html#method_get"
        },                {
            "fqsen": "\\Database\u003A\u003Areturnstmt\u0028\u0029",
            "name": "returnstmt",
            "summary": "",
            "url": "classes/Database.html#method_returnstmt"
        },                {
            "fqsen": "\\Database\u003A\u003AreturnError\u0028\u0029",
            "name": "returnError",
            "summary": "",
            "url": "classes/Database.html#method_returnError"
        },                {
            "fqsen": "\\Database\u003A\u003Afirst\u0028\u0029",
            "name": "first",
            "summary": "",
            "url": "classes/Database.html#method_first"
        },                {
            "fqsen": "\\Database\u003A\u003AlastID\u0028\u0029",
            "name": "lastID",
            "summary": "",
            "url": "classes/Database.html#method_lastID"
        },                {
            "fqsen": "\\Database\u003A\u003AdeNestWhere\u0028\u0029",
            "name": "deNestWhere",
            "summary": "",
            "url": "classes/Database.html#method_deNestWhere"
        },                {
            "fqsen": "\\Database\u003A\u003A\u0024pdo",
            "name": "pdo",
            "summary": "",
            "url": "classes/Database.html#property_pdo"
        },                {
            "fqsen": "\\Database\u003A\u003A\u0024debug",
            "name": "debug",
            "summary": "",
            "url": "classes/Database.html#property_debug"
        },                {
            "fqsen": "\\Database\u003A\u003A\u0024stmt",
            "name": "stmt",
            "summary": "",
            "url": "classes/Database.html#property_stmt"
        },                {
            "fqsen": "\\DummyData",
            "name": "DummyData",
            "summary": "",
            "url": "classes/DummyData.html"
        },                {
            "fqsen": "\\DummyData\u003A\u003AfirstNames",
            "name": "firstNames",
            "summary": "",
            "url": "classes/DummyData.html#constant_firstNames"
        },                {
            "fqsen": "\\DummyData\u003A\u003AlastNames",
            "name": "lastNames",
            "summary": "",
            "url": "classes/DummyData.html#constant_lastNames"
        },                {
            "fqsen": "\\DummyData\u003A\u003Astreets",
            "name": "streets",
            "summary": "",
            "url": "classes/DummyData.html#constant_streets"
        },                {
            "fqsen": "\\DummyData\u003A\u003Acities",
            "name": "cities",
            "summary": "",
            "url": "classes/DummyData.html#constant_cities"
        },                {
            "fqsen": "\\DummyData\u003A\u003Apayrate",
            "name": "payrate",
            "summary": "",
            "url": "classes/DummyData.html#constant_payrate"
        },                {
            "fqsen": "\\DummyData\u003A\u003Acontracthours",
            "name": "contracthours",
            "summary": "",
            "url": "classes/DummyData.html#constant_contracthours"
        },                {
            "fqsen": "\\DummyData\u003A\u003AsickLeaveReason",
            "name": "sickLeaveReason",
            "summary": "",
            "url": "classes/DummyData.html#constant_sickLeaveReason"
        },                {
            "fqsen": "\\Employee",
            "name": "Employee",
            "summary": "",
            "url": "classes/Employee.html"
        },                {
            "fqsen": "\\Employee\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Employee.html#method___construct"
        },                {
            "fqsen": "\\Employee\u003A\u003AcreateNewEmployee\u0028\u0029",
            "name": "createNewEmployee",
            "summary": "",
            "url": "classes/Employee.html#method_createNewEmployee"
        },                {
            "fqsen": "\\Employee\u003A\u003AgetDepartment\u0028\u0029",
            "name": "getDepartment",
            "summary": "",
            "url": "classes/Employee.html#method_getDepartment"
        },                {
            "fqsen": "\\Employee\u003A\u003AgetManager\u0028\u0029",
            "name": "getManager",
            "summary": "",
            "url": "classes/Employee.html#method_getManager"
        },                {
            "fqsen": "\\Employee\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "",
            "url": "classes/Employee.html#method_getPassword"
        },                {
            "fqsen": "\\Employee\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Employee.html#property_db"
        },                {
            "fqsen": "\\Employee\u003A\u003A\u0024EmployeeID",
            "name": "EmployeeID",
            "summary": "",
            "url": "classes/Employee.html#property_EmployeeID"
        },                {
            "fqsen": "\\Employee\u003A\u003A\u0024FirstName",
            "name": "FirstName",
            "summary": "",
            "url": "classes/Employee.html#property_FirstName"
        },                {
            "fqsen": "\\Employee\u003A\u003A\u0024LastName",
            "name": "LastName",
            "summary": "",
            "url": "classes/Employee.html#property_LastName"
        },                {
            "fqsen": "\\Employee\u003A\u003A\u0024Email",
            "name": "Email",
            "summary": "",
            "url": "classes/Employee.html#property_Email"
        },                {
            "fqsen": "\\Employee\u003A\u003A\u0024PhoneNumber",
            "name": "PhoneNumber",
            "summary": "",
            "url": "classes/Employee.html#property_PhoneNumber"
        },                {
            "fqsen": "\\Employee\u003A\u003A\u0024Street",
            "name": "Street",
            "summary": "",
            "url": "classes/Employee.html#property_Street"
        },                {
            "fqsen": "\\Employee\u003A\u003A\u0024HouseNumber",
            "name": "HouseNumber",
            "summary": "",
            "url": "classes/Employee.html#property_HouseNumber"
        },                {
            "fqsen": "\\Employee\u003A\u003A\u0024City",
            "name": "City",
            "summary": "",
            "url": "classes/Employee.html#property_City"
        },                {
            "fqsen": "\\Employee\u003A\u003A\u0024DateOfBirth",
            "name": "DateOfBirth",
            "summary": "",
            "url": "classes/Employee.html#property_DateOfBirth"
        },                {
            "fqsen": "\\Employee\u003A\u003A\u0024PostalCode",
            "name": "PostalCode",
            "summary": "",
            "url": "classes/Employee.html#property_PostalCode"
        },                {
            "fqsen": "\\Employee\u003A\u003A\u0024FunctionTypeID",
            "name": "FunctionTypeID",
            "summary": "",
            "url": "classes/Employee.html#property_FunctionTypeID"
        },                {
            "fqsen": "\\Employee\u003A\u003A\u0024DocumentNumberID",
            "name": "DocumentNumberID",
            "summary": "",
            "url": "classes/Employee.html#property_DocumentNumberID"
        },                {
            "fqsen": "\\Employee\u003A\u003A\u0024DepartmentID",
            "name": "DepartmentID",
            "summary": "",
            "url": "classes/Employee.html#property_DepartmentID"
        },                {
            "fqsen": "\\API\\ApiEndpointInterface",
            "name": "ApiEndpointInterface",
            "summary": "",
            "url": "classes/API-ApiEndpointInterface.html"
        },                {
            "fqsen": "\\API\\ApiEndpointInterface\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/API-ApiEndpointInterface.html#method_get"
        },                {
            "fqsen": "\\API\\ApiEndpointInterface\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "",
            "url": "classes/API-ApiEndpointInterface.html#method_put"
        },                {
            "fqsen": "\\API\\ApiEndpointInterface\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "",
            "url": "classes/API-ApiEndpointInterface.html#method_post"
        },                {
            "fqsen": "\\API\\ApiEndpointInterface\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/API-ApiEndpointInterface.html#method_delete"
        },                {
            "fqsen": "\\API\\ApiEndpointInterface\u003A\u003AvalidateEndpoint\u0028\u0029",
            "name": "validateEndpoint",
            "summary": "",
            "url": "classes/API-ApiEndpointInterface.html#method_validateEndpoint"
        },                {
            "fqsen": "\\API\\ApiEndpointInterface\u003A\u003AvalidateGet\u0028\u0029",
            "name": "validateGet",
            "summary": "",
            "url": "classes/API-ApiEndpointInterface.html#method_validateGet"
        },                {
            "fqsen": "\\API\\Contracts",
            "name": "Contracts",
            "summary": "",
            "url": "classes/API-Contracts.html"
        },                {
            "fqsen": "\\API\\Contracts\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/API-Contracts.html#method___construct"
        },                {
            "fqsen": "\\API\\Contracts\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/API-Contracts.html#method_get"
        },                {
            "fqsen": "\\API\\Contracts\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "",
            "url": "classes/API-Contracts.html#method_post"
        },                {
            "fqsen": "\\API\\Contracts\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "",
            "url": "classes/API-Contracts.html#method_put"
        },                {
            "fqsen": "\\API\\Contracts\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/API-Contracts.html#method_delete"
        },                {
            "fqsen": "\\API\\Contracts\u003A\u003AvalidateEndpoint\u0028\u0029",
            "name": "validateEndpoint",
            "summary": "",
            "url": "classes/API-Contracts.html#method_validateEndpoint"
        },                {
            "fqsen": "\\API\\Contracts\u003A\u003AvalidateGet\u0028\u0029",
            "name": "validateGet",
            "summary": "",
            "url": "classes/API-Contracts.html#method_validateGet"
        },                {
            "fqsen": "\\API\\Contracts\u003A\u003AvalidatePostRequest\u0028\u0029",
            "name": "validatePostRequest",
            "summary": "",
            "url": "classes/API-Contracts.html#method_validatePostRequest"
        },                {
            "fqsen": "\\API\\Contracts\u003A\u003A\u0024employee",
            "name": "employee",
            "summary": "",
            "url": "classes/API-Contracts.html#property_employee"
        },                {
            "fqsen": "\\API\\Contracts\u003A\u003A\u0024manager",
            "name": "manager",
            "summary": "",
            "url": "classes/API-Contracts.html#property_manager"
        },                {
            "fqsen": "\\API\\Contracts\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/API-Contracts.html#property_db"
        },                {
            "fqsen": "\\API\\Departments",
            "name": "Departments",
            "summary": "",
            "url": "classes/API-Departments.html"
        },                {
            "fqsen": "\\API\\Departments\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/API-Departments.html#method_get"
        },                {
            "fqsen": "\\API\\Departments\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "",
            "url": "classes/API-Departments.html#method_post"
        },                {
            "fqsen": "\\API\\Departments\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "",
            "url": "classes/API-Departments.html#method_put"
        },                {
            "fqsen": "\\API\\Departments\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/API-Departments.html#method_delete"
        },                {
            "fqsen": "\\API\\Departments\u003A\u003AvalidateEndpoint\u0028\u0029",
            "name": "validateEndpoint",
            "summary": "",
            "url": "classes/API-Departments.html#method_validateEndpoint"
        },                {
            "fqsen": "\\API\\Departments\u003A\u003AvalidateGet\u0028\u0029",
            "name": "validateGet",
            "summary": "",
            "url": "classes/API-Departments.html#method_validateGet"
        },                {
            "fqsen": "\\API\\Employees",
            "name": "Employees",
            "summary": "",
            "url": "classes/API-Employees.html"
        },                {
            "fqsen": "\\API\\Employees\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/API-Employees.html#method_get"
        },                {
            "fqsen": "\\API\\Employees\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "",
            "url": "classes/API-Employees.html#method_post"
        },                {
            "fqsen": "\\API\\Employees\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "",
            "url": "classes/API-Employees.html#method_put"
        },                {
            "fqsen": "\\API\\Employees\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/API-Employees.html#method_delete"
        },                {
            "fqsen": "\\API\\Employees\u003A\u003AvalidateEndpoint\u0028\u0029",
            "name": "validateEndpoint",
            "summary": "",
            "url": "classes/API-Employees.html#method_validateEndpoint"
        },                {
            "fqsen": "\\API\\Employees\u003A\u003AvalidateGet\u0028\u0029",
            "name": "validateGet",
            "summary": "",
            "url": "classes/API-Employees.html#method_validateGet"
        },                {
            "fqsen": "\\API\\Employees\u003A\u003AreturnDepartmentEmployees\u0028\u0029",
            "name": "returnDepartmentEmployees",
            "summary": "",
            "url": "classes/API-Employees.html#method_returnDepartmentEmployees"
        },                {
            "fqsen": "\\API\\Employees\u003A\u003AreturnSingleItem\u0028\u0029",
            "name": "returnSingleItem",
            "summary": "",
            "url": "classes/API-Employees.html#method_returnSingleItem"
        },                {
            "fqsen": "\\API\\Employees\u003A\u003AvalidatePostRequest\u0028\u0029",
            "name": "validatePostRequest",
            "summary": "",
            "url": "classes/API-Employees.html#method_validatePostRequest"
        },                {
            "fqsen": "\\API\\Endpoint",
            "name": "Endpoint",
            "summary": "",
            "url": "classes/API-Endpoint.html"
        },                {
            "fqsen": "\\API\\Endpoint\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/API-Endpoint.html#method___construct"
        },                {
            "fqsen": "\\API\\Endpoint\u003A\u003A\u0024employee",
            "name": "employee",
            "summary": "",
            "url": "classes/API-Endpoint.html#property_employee"
        },                {
            "fqsen": "\\API\\Endpoint\u003A\u003A\u0024manager",
            "name": "manager",
            "summary": "",
            "url": "classes/API-Endpoint.html#property_manager"
        },                {
            "fqsen": "\\API\\Endpoint\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/API-Endpoint.html#property_db"
        },                {
            "fqsen": "\\API\\Faq",
            "name": "Faq",
            "summary": "",
            "url": "classes/API-Faq.html"
        },                {
            "fqsen": "\\API\\Faq\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/API-Faq.html#method_get"
        },                {
            "fqsen": "\\API\\Faq\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "",
            "url": "classes/API-Faq.html#method_put"
        },                {
            "fqsen": "\\API\\Faq\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "",
            "url": "classes/API-Faq.html#method_post"
        },                {
            "fqsen": "\\API\\Faq\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/API-Faq.html#method_delete"
        },                {
            "fqsen": "\\API\\Faq\u003A\u003AvalidateEndpoint\u0028\u0029",
            "name": "validateEndpoint",
            "summary": "",
            "url": "classes/API-Faq.html#method_validateEndpoint"
        },                {
            "fqsen": "\\API\\Faq\u003A\u003AvalidateGet\u0028\u0029",
            "name": "validateGet",
            "summary": "",
            "url": "classes/API-Faq.html#method_validateGet"
        },                {
            "fqsen": "\\API\\Holidays",
            "name": "Holidays",
            "summary": "",
            "url": "classes/API-Holidays.html"
        },                {
            "fqsen": "\\API\\Holidays\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/API-Holidays.html#method_get"
        },                {
            "fqsen": "\\API\\Holidays\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "",
            "url": "classes/API-Holidays.html#method_post"
        },                {
            "fqsen": "\\API\\Holidays\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "",
            "url": "classes/API-Holidays.html#method_put"
        },                {
            "fqsen": "\\API\\Holidays\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/API-Holidays.html#method_delete"
        },                {
            "fqsen": "\\API\\Holidays\u003A\u003AvalidateEndpoint\u0028\u0029",
            "name": "validateEndpoint",
            "summary": "",
            "url": "classes/API-Holidays.html#method_validateEndpoint"
        },                {
            "fqsen": "\\API\\Holidays\u003A\u003AvalidateGet\u0028\u0029",
            "name": "validateGet",
            "summary": "",
            "url": "classes/API-Holidays.html#method_validateGet"
        },                {
            "fqsen": "\\API\\Hours",
            "name": "Hours",
            "summary": "",
            "url": "classes/API-Hours.html"
        },                {
            "fqsen": "\\API\\Hours\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/API-Hours.html#method_get"
        },                {
            "fqsen": "\\API\\Hours\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "",
            "url": "classes/API-Hours.html#method_put"
        },                {
            "fqsen": "\\API\\Hours\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "",
            "url": "classes/API-Hours.html#method_post"
        },                {
            "fqsen": "\\API\\Hours\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/API-Hours.html#method_delete"
        },                {
            "fqsen": "\\API\\Hours\u003A\u003AvalidateEndpoint\u0028\u0029",
            "name": "validateEndpoint",
            "summary": "",
            "url": "classes/API-Hours.html#method_validateEndpoint"
        },                {
            "fqsen": "\\API\\Hours\u003A\u003AvalidateGet\u0028\u0029",
            "name": "validateGet",
            "summary": "",
            "url": "classes/API-Hours.html#method_validateGet"
        },                {
            "fqsen": "\\API\\BadRequestException",
            "name": "BadRequestException",
            "summary": "",
            "url": "classes/API-BadRequestException.html"
        },                {
            "fqsen": "\\API\\BadRequestException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/API-BadRequestException.html#method___construct"
        },                {
            "fqsen": "\\API\\BadRequestException\u003A\u003AgetError\u0028\u0029",
            "name": "getError",
            "summary": "",
            "url": "classes/API-BadRequestException.html#method_getError"
        },                {
            "fqsen": "\\API\\BadRequestException\u003A\u003A\u0024error",
            "name": "error",
            "summary": "",
            "url": "classes/API-BadRequestException.html#property_error"
        },                {
            "fqsen": "\\API\\DatabaseConnectionException",
            "name": "DatabaseConnectionException",
            "summary": "",
            "url": "classes/API-DatabaseConnectionException.html"
        },                {
            "fqsen": "\\API\\DatabaseConnectionException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/API-DatabaseConnectionException.html#method___construct"
        },                {
            "fqsen": "\\API\\DatabaseConnectionException\u003A\u003AgetError\u0028\u0029",
            "name": "getError",
            "summary": "",
            "url": "classes/API-DatabaseConnectionException.html#method_getError"
        },                {
            "fqsen": "\\API\\DatabaseConnectionException\u003A\u003A\u0024error",
            "name": "error",
            "summary": "",
            "url": "classes/API-DatabaseConnectionException.html#property_error"
        },                {
            "fqsen": "\\API\\NotAuthorizedException",
            "name": "NotAuthorizedException",
            "summary": "",
            "url": "classes/API-NotAuthorizedException.html"
        },                {
            "fqsen": "\\API\\NotAuthorizedException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/API-NotAuthorizedException.html#method___construct"
        },                {
            "fqsen": "\\API\\NotAuthorizedException\u003A\u003AgetError\u0028\u0029",
            "name": "getError",
            "summary": "",
            "url": "classes/API-NotAuthorizedException.html#method_getError"
        },                {
            "fqsen": "\\API\\NotAuthorizedException\u003A\u003A\u0024error",
            "name": "error",
            "summary": "",
            "url": "classes/API-NotAuthorizedException.html#property_error"
        },                {
            "fqsen": "\\API\\NotFoundException",
            "name": "NotFoundException",
            "summary": "",
            "url": "classes/API-NotFoundException.html"
        },                {
            "fqsen": "\\API\\NotFoundException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/API-NotFoundException.html#method___construct"
        },                {
            "fqsen": "\\API\\NotFoundException\u003A\u003AgetError\u0028\u0029",
            "name": "getError",
            "summary": "",
            "url": "classes/API-NotFoundException.html#method_getError"
        },                {
            "fqsen": "\\API\\NotFoundException\u003A\u003A\u0024error",
            "name": "error",
            "summary": "",
            "url": "classes/API-NotFoundException.html#property_error"
        },                {
            "fqsen": "\\API\\TeapotException",
            "name": "TeapotException",
            "summary": "",
            "url": "classes/API-TeapotException.html"
        },                {
            "fqsen": "\\API\\TeapotException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/API-TeapotException.html#method___construct"
        },                {
            "fqsen": "\\API\\TeapotException\u003A\u003AgetError\u0028\u0029",
            "name": "getError",
            "summary": "",
            "url": "classes/API-TeapotException.html#method_getError"
        },                {
            "fqsen": "\\API\\TeapotException\u003A\u003A\u0024error",
            "name": "error",
            "summary": "",
            "url": "classes/API-TeapotException.html#property_error"
        },                {
            "fqsen": "\\Hash",
            "name": "Hash",
            "summary": "",
            "url": "classes/Hash.html"
        },                {
            "fqsen": "\\Hash\u003A\u003Amake\u0028\u0029",
            "name": "make",
            "summary": "",
            "url": "classes/Hash.html#method_make"
        },                {
            "fqsen": "\\Hash\u003A\u003Averify\u0028\u0029",
            "name": "verify",
            "summary": "",
            "url": "classes/Hash.html#method_verify"
        },                {
            "fqsen": "\\Installer",
            "name": "Installer",
            "summary": "",
            "url": "classes/Installer.html"
        },                {
            "fqsen": "\\Installer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Installer.html#method___construct"
        },                {
            "fqsen": "\\Installer\u003A\u003AinstallSQL\u0028\u0029",
            "name": "installSQL",
            "summary": "",
            "url": "classes/Installer.html#method_installSQL"
        },                {
            "fqsen": "\\Installer\u003A\u003AinsertRandomEmployee\u0028\u0029",
            "name": "insertRandomEmployee",
            "summary": "",
            "url": "classes/Installer.html#method_insertRandomEmployee"
        },                {
            "fqsen": "\\Installer\u003A\u003AcreateEmployees\u0028\u0029",
            "name": "createEmployees",
            "summary": "",
            "url": "classes/Installer.html#method_createEmployees"
        },                {
            "fqsen": "\\Installer\u003A\u003AinsertRandomHours\u0028\u0029",
            "name": "insertRandomHours",
            "summary": "",
            "url": "classes/Installer.html#method_insertRandomHours"
        },                {
            "fqsen": "\\Installer\u003A\u003AinsertDuplicateEntries\u0028\u0029",
            "name": "insertDuplicateEntries",
            "summary": "",
            "url": "classes/Installer.html#method_insertDuplicateEntries"
        },                {
            "fqsen": "\\Installer\u003A\u003AcreateRandomSickLeave\u0028\u0029",
            "name": "createRandomSickLeave",
            "summary": "",
            "url": "classes/Installer.html#method_createRandomSickLeave"
        },                {
            "fqsen": "\\Installer\u003A\u003AcreateRandomHolidays\u0028\u0029",
            "name": "createRandomHolidays",
            "summary": "",
            "url": "classes/Installer.html#method_createRandomHolidays"
        },                {
            "fqsen": "\\Installer\u003A\u003ArandomLetter\u0028\u0029",
            "name": "randomLetter",
            "summary": "",
            "url": "classes/Installer.html#method_randomLetter"
        },                {
            "fqsen": "\\Installer\u003A\u003AcreateDates\u0028\u0029",
            "name": "createDates",
            "summary": "",
            "url": "classes/Installer.html#method_createDates"
        },                {
            "fqsen": "\\Installer\u003A\u003AreturnStatus\u0028\u0029",
            "name": "returnStatus",
            "summary": "",
            "url": "classes/Installer.html#method_returnStatus"
        },                {
            "fqsen": "\\Installer\u003A\u003AcreateENV\u0028\u0029",
            "name": "createENV",
            "summary": "",
            "url": "classes/Installer.html#method_createENV"
        },                {
            "fqsen": "\\Installer\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Installer.html#property_db"
        },                {
            "fqsen": "\\Installer\u003A\u003A\u0024numEmp",
            "name": "numEmp",
            "summary": "",
            "url": "classes/Installer.html#property_numEmp"
        },                {
            "fqsen": "\\Installer\u003A\u003A\u0024hashedPassword",
            "name": "hashedPassword",
            "summary": "",
            "url": "classes/Installer.html#property_hashedPassword"
        },                {
            "fqsen": "\\Installer\u003A\u003A\u0024firstNames",
            "name": "firstNames",
            "summary": "",
            "url": "classes/Installer.html#property_firstNames"
        },                {
            "fqsen": "\\Installer\u003A\u003A\u0024lastNames",
            "name": "lastNames",
            "summary": "",
            "url": "classes/Installer.html#property_lastNames"
        },                {
            "fqsen": "\\Installer\u003A\u003A\u0024streets",
            "name": "streets",
            "summary": "",
            "url": "classes/Installer.html#property_streets"
        },                {
            "fqsen": "\\Installer\u003A\u003A\u0024cities",
            "name": "cities",
            "summary": "",
            "url": "classes/Installer.html#property_cities"
        },                {
            "fqsen": "\\Installer\u003A\u003A\u0024payrate",
            "name": "payrate",
            "summary": "",
            "url": "classes/Installer.html#property_payrate"
        },                {
            "fqsen": "\\Installer\u003A\u003A\u0024contracthours",
            "name": "contracthours",
            "summary": "",
            "url": "classes/Installer.html#property_contracthours"
        },                {
            "fqsen": "\\Installer\u003A\u003A\u0024sickleave",
            "name": "sickleave",
            "summary": "",
            "url": "classes/Installer.html#property_sickleave"
        },                {
            "fqsen": "\\Installer\u003A\u003A\u0024dates",
            "name": "dates",
            "summary": "",
            "url": "classes/Installer.html#property_dates"
        },                {
            "fqsen": "\\Installer\u003A\u003A\u0024namespace",
            "name": "namespace",
            "summary": "",
            "url": "classes/Installer.html#property_namespace"
        },                {
            "fqsen": "\\Installer\u003A\u003A\u0024return",
            "name": "return",
            "summary": "",
            "url": "classes/Installer.html#property_return"
        },                {
            "fqsen": "\\Mailer",
            "name": "Mailer",
            "summary": "",
            "url": "classes/Mailer.html"
        },                {
            "fqsen": "\\Mailer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Mailer\u0020constructor.",
            "url": "classes/Mailer.html#method___construct"
        },                {
            "fqsen": "\\Mailer\u003A\u003Averify\u0028\u0029",
            "name": "verify",
            "summary": "",
            "url": "classes/Mailer.html#method_verify"
        },                {
            "fqsen": "\\Mailer\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "",
            "url": "classes/Mailer.html#method_send"
        },                {
            "fqsen": "\\Mailer\u003A\u003A\u0024mail",
            "name": "mail",
            "summary": "",
            "url": "classes/Mailer.html#property_mail"
        },                {
            "fqsen": "\\Mailer\u003A\u003A\u0024recipient",
            "name": "recipient",
            "summary": "",
            "url": "classes/Mailer.html#property_recipient"
        },                {
            "fqsen": "\\Mailer\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Mailer.html#property_name"
        },                {
            "fqsen": "\\Mailer\u003A\u003A\u0024subject",
            "name": "subject",
            "summary": "",
            "url": "classes/Mailer.html#property_subject"
        },                {
            "fqsen": "\\Mailer\u003A\u003A\u0024content",
            "name": "content",
            "summary": "",
            "url": "classes/Mailer.html#property_content"
        },                {
            "fqsen": "\\Mailer\u003A\u003A\u0024success",
            "name": "success",
            "summary": "",
            "url": "classes/Mailer.html#property_success"
        },                {
            "fqsen": "\\UUID",
            "name": "UUID",
            "summary": "UUID\u0020class",
            "url": "classes/UUID.html"
        },                {
            "fqsen": "\\UUID\u003A\u003Av3\u0028\u0029",
            "name": "v3",
            "summary": "Generate\u0020v3\u0020UUID",
            "url": "classes/UUID.html#method_v3"
        },                {
            "fqsen": "\\UUID\u003A\u003Av4\u0028\u0029",
            "name": "v4",
            "summary": "Generate\u0020v4\u0020UUID",
            "url": "classes/UUID.html#method_v4"
        },                {
            "fqsen": "\\UUID\u003A\u003Av5\u0028\u0029",
            "name": "v5",
            "summary": "Generate\u0020v5\u0020UUID",
            "url": "classes/UUID.html#method_v5"
        },                {
            "fqsen": "\\UUID\u003A\u003Ais_valid\u0028\u0029",
            "name": "is_valid",
            "summary": "",
            "url": "classes/UUID.html#method_is_valid"
        },                {
            "fqsen": "\\UUID\u003A\u003AcreateRandomUUID\u0028\u0029",
            "name": "createRandomUUID",
            "summary": "",
            "url": "classes/UUID.html#method_createRandomUUID"
        },                {
            "fqsen": "\\PHPUnit\\Test\\EmployeesTest",
            "name": "EmployeesTest",
            "summary": "",
            "url": "classes/PHPUnit-Test-EmployeesTest.html"
        },                {
            "fqsen": "\\PHPUnit\\Test\\EmployeesTest\u003A\u003AtestGet\u0028\u0029",
            "name": "testGet",
            "summary": "",
            "url": "classes/PHPUnit-Test-EmployeesTest.html#method_testGet"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\API",
            "name": "API",
            "summary": "",
            "url": "namespaces/api.html"
        },                {
            "fqsen": "\\PHPUnit\\Test",
            "name": "Test",
            "summary": "",
            "url": "namespaces/phpunit-test.html"
        },                {
            "fqsen": "\\PHPUnit",
            "name": "PHPUnit",
            "summary": "",
            "url": "namespaces/phpunit.html"
        }            ]
);
