<?php


class DummyData
{
    const firstNames = [
        'Lodewijk',
        'Boudewijn',
        'Dolf',
        'Jaap',
        'Gisele',
        'Wendelmoed',
        'Fiachna',
        'Misty',
        'Sunny',
        'Odette',
        'Marie',
        'Jean',
        'Marc',
        'Michel',
        'Patrick',
        'Luc',
        'André',
        'Jan',
        'Monique',
        'Philippe',
        'Martine',
        'Anne',
        'Paul',
        'Nathalie',
        'Pierre',
        'Roger',
        'Willy',
        'Nicole',
        'Anna',
        'Rita',
        'Eric',
        'Christiane',
        'Marcel',
        'Johan',
        'Peter',
        'Jacques',
        'Dirk',
        'Alain',
        'Robert',
        'Daniel',
        'David',
        'Christine',
        'Jacqueline',
        'Joseph',
        'Thomas',
        'Jozef',
        'Isabelle',
        'Bart',
        'François',
        'Nicolas',
        'Christian',
        'Tom',
        'Guy',
        'Christophe',
        'Jeannine',
        'Olivier',
        'Sarah',
        'Patricia',
        'Ann'
    ];
    const lastNames = [
        'Olivander',
        'van Kalekoen',
        'Merel',
        'Wildevuur',
        'Bathilde',
        'Hooggeboren',
        'McCann',
        'Squirtle',
        'Moon',
        'Zwaan',
        'Jansen',
        'de Vries',
        'van Dijk',
        'Bakker',
        'Janssen',
        'Visser',
        'Smit',
        'de Boer',
        'Mulder',
        'de Groot',
        'Bos',
        'Vos',
        'Peters',
        'Hendriks',
        'van Leeuwen',
        'Dekker',
        'Brouwer',
        'de Wit',
        'Dijkstra',
        'Smits',
        'de Graaf',
        'van der Linden',
        'Kok',
        'Jacobs',
        'de Haan',
        'Vermeulen',
        'van den Heuvel',
        'van den Broek',
        'de Bruin',
        'Schouten',
        'van Beek',
        'Willems',
        'van Vliet',
        'Hoekstra',
        'Maas',
        'Verhoeven',
        'Koster',
        'van Dam',
        'Prins',
        'Blom',
        'Huisman',
        'Peeters',
        'de Jonge',
        'Kuipers',
        'van Veen',
        'Post',
        'Kuiper',
        'Veenstra',
        'Kramer',
        'Scholten',
        'van Wijk',
        'Postma',
        'Martens',
        'Vink',
        'de Ruiter',
        'Timmermans',
        'Groen',
        'Gerritsen',
        'Jonker',
        'van Loon',
        'Boer',
        'Willemsen',
        'Smeets',
        'de Lange',
        'de Vos',
        'Bosch',
        'van Dongen',
        'Schipper',
        'de Koning',
        'van der Laan',
        'Koning',
        'Driessen',
        'van Doorn',
        'Hermans',
        'Evers',
        'van den Bosch',
        'van der Meulen',
        'Hofman',
        'Bosman',
        'Wolters',
        'Sanders',
        'van der Horst',
        'Mol',
        'Molenaar',
        'de Leeuw',
        'Verbeek'
    ];
    const streets = [
        'De Sesamstraat',
        'Oranje Pan',
        'Kerkstraat',
        'Schoolstraat',
        'Molenstraat',
        'Dorpsstraat',
        'Molenweg',
        'Julianastraat',
        'Parallelweg',
        'Nieuwstraat',
        'Wilhelminastraat',
        'Sportlaan',
        'Industrieweg',
        'Beatrixstraat',
        'Kastanjelaan',
        'Stationsweg',
        'Eikenlaan',
        'Markt',
        'Prins Bernhardstraat',
        'Emmastraat',
        'Beukenlaan'
    ];

    const cities = [
        'Amsterdam',
        'Rotterdam',
        'Den Haag',
        'Utrecht',
        'Eindhoven',
        'Groningen',
        'Tilburg',
        'Almere',
        'Breda',
        'Nijmegen',
        'Apeldoorn',
        'Haarlem',
        'Arnhem',
        'Enschede',
        'Haarlemmermeer',
        'Amersfoort',
        'Zaanstad',
        'Zwolle',
        'Zoetermeer',
        'Leeuwarden',
        'Leiden',
        'Maastricht',
        'Dordrecht',
        'Ede',
        'Alphen aan den Rijn',
        'Westland',
        'Alkmaar',
        'Emmen',
        'Delft',
        'Venlo',
        'Deventer'];
}
